name: defood
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # Assets
  cupertino_icons: ^1.0.2
  liquid_swipe: ^2.0.1
  lottie: ^1.0.1
  carousel_slider: ^3.0.0
  bottom_navy_bar: ^5.6.0
  styled_text: ^1.0.3
  intl: ^0.17.0

  # Firebase
  firebase_analytics: ^5.0.2

  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.3
  firebase_dynamic_links: ^0.5.1

  firebase_database: ^6.1.1
  firebase_core: ^1.0.2

  # Shared preferences
  shared_preferences: ^2.0.5

  # Provider
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/food1.png
    - assets/images/food2.png
    - assets/images/food3.png
    - assets/images/food4.png
    - assets/images/food5.png
    - assets/images/food6.png
    - assets/images/food7.png
    - assets/images/food8.png
    - assets/images/food9.png
    - assets/images/google_logo.png
    - assets/images/categories/bread.png
    - assets/images/categories/drinks.png
    - assets/images/categories/desserts.png
    - assets/images/categories/fast_food.png
    - assets/images/categories/healthy_food.png
    - assets/images/categories/meat.png
    - assets/images/categories/noodle.png
    - assets/images/categories/pizza.png
    - assets/images/categories/rice.png
    - assets/images/categories/snacks.png
    - assets/images/bike.png
    - assets/images/takeout.png
    - assets/images/logo1.png
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts: 
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 500
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
